FROM --platform=linux/amd64 python:3.11
RUN pip install --no-cache-dir \
    pandas==2.1.4 \
    snowflake-connector-python==3.7.1 \
    snowflake-sqlalchemy==1.5.1 \
    tqdm==4.66.2 \
    lancedb==0.5.7 \
    llama_index==0.10.27 \
    llama-index-vector-stores-lancedb==0.1.3 \
    pyyaml==6.0.1 \
    dbt-core==1.7.11 \
    dbt-snowflake==1.7.3 \