select
    BROWSER,
    CITY,
    REGION,
    COUNTRY,
    "dateHourMinute" as DATE_HOUR_MINUTE,
    "deviceCategory" as DEVICE_CATEGORY,
    "eventName" as EVENT_NAME,
    "fullPageUrl" as FULL_PAGE_URL,
    "landingPage" as LANDING_PAGE,
    "activeUsers" as ACTIVE_USERS,
    "averageSessionDuration" as AVERAGE_SESSION_DURATION,
    "engagementRate" as ENGAGEMENT_RATE,
    "bounceRate" as BOUNCE_RATE,
    "SESSIONS",
    API_QUERY_DATE,
    API_QUERY_START_DATE,
    API_QUERY_END_DATE,
from {{ source('google_analytics', 'ga_base_table') }}